Repository wrappid/communication-module, pull requests merged in 2024-02, with the labels that each got.

#13 fix: :bug: Correct the typo
  app/styles/DefaultModuleStyles.js
  app/styles/LargeModuleStyles.js
  app/styles/MediumModuleStyles.js
  app/styles/SmallModuleStyles.js
  app/styles/XLargeModuleStyles.js
  app/styles/XXLargeModuleStyles.js
Labels: 🐞 bug

#15 feat: move to typescript
  service/controllers.registry.js
  service/controllers.registry.ts
  service/controllers/communication.controller.js
  service/controllers/communication.controller.ts
  service/functions.registry.js
  service/functions.registry.ts
  service/functions/communication.functions.js
  service/functions/communication.functions.ts
  service/middlewares.registry.js
  service/middlewares.registry.ts
  service/models.registry.ts
  service/models/CommunicationHistory.model.ts
  service/models/CommunicationTemplates.model.ts
  service/models/MailComms.model.ts
  service/models/Otp.model.ts
  service/models/SmsComms.model.ts
  service/models/TestDatas.model.js
  service/models/TestDatas.model.ts
  service/models/WhatsAppComms.model.ts
  service/routes.registry.js
  service/routes.registry.ts
  service/routes/communication.routes.js
  service/routes/communication.routes.ts
  service/tasks.registry.js
  service/tasks.registry.ts
  service/tasks/CommTask.js
  service/tasks/CommTask.ts
  service/validations.registry.js
  service/validations.registry.ts
Labels: enhancement

#17 Wrpd enhancement 16
  .eslint/service/.eslintrc.js
  .eslintrc.js
  .github/scripts/attribution_header_adder.sh
  .github/workflows/auto-create-and-merge-pr.yml
  package-lock.json
  package.json
  service/functions/test.functions.ts
  service/models/CommunicationTemplates.model.ts
  service/models/MailComms.model.ts
  service/models/Otp.model.ts
  service/models/SmsComms.model.ts
  service/models/WhatsAppComms.model.ts
Labels: enhancement

#20 fix(config): :ambulance: correct wrappid.meta.json
  .wrappid/wrappid.meta.json
Labels: bugfix

#21 merge: development into main
  .wrappid/wrappid.meta.json
Labels: bugfix
